name: emnist_digits_regularized
experiment_id: Ext2.2

model:
  mode: dense
  d_hidden: 256
  n_layer: 1
  variance_corrected_init: false

training:
  epochs: 100
  lr: 0.001
  batch_size: 2048

regularization:
  noise_std: 0.15
  weight_decay: 0.5

data:
  dataset: emnist_digits
