name: mnist_dense_full
experiment_id: P1.4

model:
  mode: dense
  d_hidden: 256
  n_layer: 1
  variance_corrected_init: false  # Push into Rich Training regime

training:
  epochs: 100
  lr: 0.001
  batch_size: 2048

regularization:
  noise_std: 0.5
  weight_decay: 1.0

data:
  dataset: mnist
